name: CI Workflow

on:
  push:
    branches:
      - tanu          # Trigger on push to 'main' branch
               # Trigger on push to any feature branch
  pull_request:
    branches:
      - tanu   # Trigger on pull requests to 'main' branch

jobs:
  test :
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
      - run: npm install
      - run: npm run build
