name: CI Workflow

on:
  push:
    branches:
      - tanu
  pull_request:
    branches:
      - tanu

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies with npm ci
        working-directory: my-app
        run: npm ci

      - name: Install other missing dependencies (if needed)
        working-directory: my-app
        run: npm install
