name: CI Workflow

on:
  push:
    branches:
      - tanu          # Trigger on push to 'main' branch
               # Trigger on push to any feature branch
  pull_request:
    branches:
      - tanu   # Trigger on pull requests to 'main' branch

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Add Git safe directory configuration
      - name: Set up Git to recognize safe directory
        run: git config --global --add safe.directory /home/runner/work/blog

      # Install dependencies for the root package (blog/package.json)
      - name: Install dependencies in the root folder (blog)
        working-directory: ./  # This will point to the root directory of the repo
        run: |
          npm install

      # Install dependencies for the frontend (my-app/package.json)
      - name: Install dependencies in the frontend (my-app)
        working-directory: ./my-app  # This will point to the 'my-app' directory
        run: |
          npm install

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git to recognize safe directory
        run: git config --global --add safe.directory /home/runner/work/blog

      - name: Lint root code (blog)
        working-directory: ./  # This will point to the root folder (blog)
        run: |
          npm run lint

      - name: Lint frontend code (my-app)
        working-directory: ./my-app  # This will point to the 'my-app' folder
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git to recognize safe directory
        run: git config --global --add safe.directory /home/runner/work/blog

      - name: Build root project (blog)
        working-directory: ./  # This will point to the root folder (blog)
        run: |
          npm run build

      - name: Build frontend project (my-app)
        working-directory: ./my-app  # This will point to the 'my-app' folder
        run: |
          npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git to recognize safe directory
        run: git config --global --add safe.directory /home/runner/work/blog

      - name: Run tests for root (blog)
        working-directory: ./  # This will point to the root folder (blog)
        run: |
          npm test

      - name: Run tests for frontend (my-app)
        working-directory: ./my-app  # This will point to the 'my-app' folder
        run: |
          npm test
