name: CI Workflow

on:
  push:
    branches:
      - tanu          # Trigger on push to 'main' branch
               # Trigger on push to any feature branch
  pull_request:
    branches:
      - tanu          # Trigger on pull requests to 'main' branch

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

  # Install dependencies for root and frontend
  install:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies in the root directory (blog)
      - name: Install dependencies in the root directory
        working-directory: ./  # root folder
        run: |
          npm install

      # Install dependencies in frontend (my-app)
      - name: Install dependencies in frontend (my-app)
        working-directory: ./my-app  # frontend folder
        run: |
          npm install

  # Lint the code for both root and frontend
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run linting in root directory (blog)
      - name: Lint root directory code
        working-directory: ./  # root folder
        run: |
          npm run lint         # Assuming root package.json has a lint script

      # Run linting in frontend directory (my-app)
      - name: Lint frontend code
        working-directory: ./my-app  # frontend folder
        run: |
          npm run lint         # Assuming frontend package.json has a lint script

  # Build both root and frontend
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build root project (blog)
      - name: Build root project
        working-directory: ./  # root folder
        run: |
          npm run build         # Assuming root package.json has a build script

      # Build frontend project (my-app)
      - name: Build frontend project
        working-directory: ./my-app   # frontend folder
        run: |
          npm run build         # Assuming frontend package.json has a build script

  # Run tests for both root and frontend
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run tests for root project (blog)
      - name: Run tests for root
        working-directory: ./  # root folder
        run: |
          npm test              # Assuming root package.json has a test script

      # Run tests for frontend project (my-app)
      - name: Run tests for frontend
        working-directory: ./my-app  # frontend folder
        run: |
          npm test              # Assuming frontend package.json has a test script
